
name: Test
on: [push, pull_request]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        gemfile:
          - Gemfile
          - gemfiles/Gemfile-rails-6-1
          - gemfiles/Gemfile-rails-6-0
          - gemfiles/Gemfile-rails-5-2
          - gemfiles/Gemfile-rails-5-1
          - gemfiles/Gemfile-rails-5-0
          - gemfiles/Gemfile-rails-4-2
        ruby:
          - '3.3'
          - '3.2'
          - '3.1'
          - '3.0'
          - '2.7'
          - '2.6'
          - '2.5'
          - '2.4'
          - '2.3'
          - '2.2'
          - '2.1'
          - '2.0'
          - '1.9'
        exclude:
          - gemfile: Gemfile
            ruby: '2.4'
          - gemfile: Gemfile
            ruby: '2.3'
          - gemfile: Gemfile
            ruby: '2.2'
          - gemfile: Gemfile
            ruby: '2.1'
          - gemfile: Gemfile
            ruby: '2.0'
          - gemfile: Gemfile
            ruby: '1.9'
          - gemfile: gemfiles/Gemfile-rails-6-1
            ruby: '2.4'
          - gemfile: gemfiles/Gemfile-rails-6-1
            ruby: '2.3'
          - gemfile: gemfiles/Gemfile-rails-6-1
            ruby: '2.2'
          - gemfile: gemfiles/Gemfile-rails-6-1
            ruby: '2.1'
          - gemfile: gemfiles/Gemfile-rails-6-1
            ruby: '2.0'
          - gemfile: gemfiles/Gemfile-rails-6-1
            ruby: '1.9'
          - gemfile: gemfiles/Gemfile-rails-6-0
            ruby: '3.3'
          - gemfile: gemfiles/Gemfile-rails-6-0
            ruby: '3.2'
          - gemfile: gemfiles/Gemfile-rails-6-0
            ruby: '3.1'
          - gemfile: gemfiles/Gemfile-rails-6-0
            ruby: '2.4'
          - gemfile: gemfiles/Gemfile-rails-6-0
            ruby: '2.3'
          - gemfile: gemfiles/Gemfile-rails-6-0
            ruby: '2.2'
          - gemfile: gemfiles/Gemfile-rails-6-0
            ruby: '2.1'
          - gemfile: gemfiles/Gemfile-rails-6-0
            ruby: '2.0'
          - gemfile: gemfiles/Gemfile-rails-6-0
            ruby: '1.9'
          - gemfile: gemfiles/Gemfile-rails-5-2
            ruby: '3.3'
          - gemfile: gemfiles/Gemfile-rails-5-2
            ruby: '3.2'
          - gemfile: gemfiles/Gemfile-rails-5-2
            ruby: '3.1'
          - gemfile: gemfiles/Gemfile-rails-5-2
            ruby: '3.0'
          - gemfile: gemfiles/Gemfile-rails-5-2
            ruby: '2.7'
          - gemfile: gemfiles/Gemfile-rails-5-2
            ruby: '2.1'
          - gemfile: gemfiles/Gemfile-rails-5-2
            ruby: '2.0'
          - gemfile: gemfiles/Gemfile-rails-5-2
            ruby: '1.9'
          - gemfile: gemfiles/Gemfile-rails-5-1
            ruby: '3.3'
          - gemfile: gemfiles/Gemfile-rails-5-1
            ruby: '3.2'
          - gemfile: gemfiles/Gemfile-rails-5-1
            ruby: '3.1'
          - gemfile: gemfiles/Gemfile-rails-5-1
            ruby: '3.0'
          - gemfile: gemfiles/Gemfile-rails-5-1
            ruby: '2.7'
          - gemfile: gemfiles/Gemfile-rails-5-1
            ruby: '2.6'
          - gemfile: gemfiles/Gemfile-rails-5-1
            ruby: '2.1'
          - gemfile: gemfiles/Gemfile-rails-5-1
            ruby: '2.0'
          - gemfile: gemfiles/Gemfile-rails-5-1
            ruby: '1.9'
          - gemfile: gemfiles/Gemfile-rails-5-0
            ruby: '3.3'
          - gemfile: gemfiles/Gemfile-rails-5-0
            ruby: '3.2'
          - gemfile: gemfiles/Gemfile-rails-5-0
            ruby: '3.1'
          - gemfile: gemfiles/Gemfile-rails-5-0
            ruby: '3.0'
          - gemfile: gemfiles/Gemfile-rails-5-0
            ruby: '2.7'
          - gemfile: gemfiles/Gemfile-rails-5-0
            ruby: '2.6'
          - gemfile: gemfiles/Gemfile-rails-5-0
            ruby: '2.5'
          - gemfile: gemfiles/Gemfile-rails-5-0
            ruby: '2.1'
          - gemfile: gemfiles/Gemfile-rails-5-0
            ruby: '2.0'
          - gemfile: gemfiles/Gemfile-rails-5-0
            ruby: '1.9'
    runs-on: ubuntu-latest
    env: # $BUNDLE_GEMFILE must be set at the job level, so it is set for all steps
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs bundle install and caches installed gems automatically
      # Add or replace database setup steps here
      - name: Set up database schema
        run: bundle exec rake db:schema:load
      - run: bundle exec rspec
